### ISSUE TITLE
Visualization question

### ISSUE THREAD

**Issue by CleyLyChen** [OpenNLPLab/FNAC_AVL#2]
Hi, Great work!
I trained fnac model on Epic-Kitchens-100 dataset, and its ciou performance is good, but its visualization results seems not right, here are some cases on Epic-Kitchens-100 dataset, the red box is GT, Do you know what's the problem with it? looking forward to your reply!
![image](https://github.com/OpenNLPLab/FNAC_AVL/assets/96591070/8cf615c8-9715-46d3-ac7b-41a327f9627c)
![image](https://github.com/OpenNLPLab/FNAC_AVL/assets/96591070/101e8b35-b74c-42c8-bf9f-fce329d15597)
![image](https://github.com/OpenNLPLab/FNAC_AVL/assets/96591070/974b381f-abc8-40ae-a935-0dc0a84025e5)

**Comment by weixuansun** [comment]
Sorry,  I am not sure why this happens. 
Seems like a figure saving issue, perhaps check if your heatmap has value overflow larger than [0,1] or [0,255].
